[2024-11-26T18:06:04.509+0000] {processor.py:186} INFO - Started process (PID=57) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:06:04.510+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:06:04.513+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:06:04.512+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:06:04.536+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:06:04.532+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Airflow-DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Airflow-DAG.py", line 5, in <module>
    import dvc.api
ModuleNotFoundError: No module named 'dvc'
[2024-11-26T18:06:04.537+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:06:04.556+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.052 seconds
[2024-11-26T18:06:34.767+0000] {processor.py:186} INFO - Started process (PID=121) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:06:34.767+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:06:34.769+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:06:34.769+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:06:34.783+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:06:34.780+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Airflow-DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Airflow-DAG.py", line 5, in <module>
    import dvc.api
ModuleNotFoundError: No module named 'dvc'
[2024-11-26T18:06:34.784+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:06:34.802+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.039 seconds
[2024-11-26T18:07:04.892+0000] {processor.py:186} INFO - Started process (PID=185) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:07:04.893+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:07:04.895+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:07:04.895+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:07:04.910+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:07:04.907+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Airflow-DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Airflow-DAG.py", line 5, in <module>
    import dvc.api
ModuleNotFoundError: No module named 'dvc'
[2024-11-26T18:07:04.912+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:07:04.926+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.038 seconds
[2024-11-26T18:07:35.846+0000] {processor.py:186} INFO - Started process (PID=255) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:07:35.846+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:07:35.848+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:07:35.848+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:07:35.864+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:07:35.861+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Airflow-DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Airflow-DAG.py", line 5, in <module>
    import dvc.api
ModuleNotFoundError: No module named 'dvc'
[2024-11-26T18:07:35.865+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:07:35.880+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.039 seconds
[2024-11-26T18:08:06.465+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:08:06.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:08:06.468+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:08:06.468+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:08:06.483+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:08:06.480+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Airflow-DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Airflow-DAG.py", line 5, in <module>
    import dvc.api
ModuleNotFoundError: No module named 'dvc'
[2024-11-26T18:08:06.484+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:08:06.499+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.037 seconds
[2024-11-26T18:08:37.194+0000] {processor.py:186} INFO - Started process (PID=383) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:08:37.194+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:08:37.196+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:08:37.196+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:08:37.210+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:08:37.207+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Airflow-DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Airflow-DAG.py", line 5, in <module>
    import dvc.api
ModuleNotFoundError: No module named 'dvc'
[2024-11-26T18:08:37.211+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:08:37.225+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.035 seconds
[2024-11-26T18:09:07.987+0000] {processor.py:186} INFO - Started process (PID=448) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:09:07.987+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:09:07.989+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:09:07.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:09:08.004+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:09:08.000+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Airflow-DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Airflow-DAG.py", line 5, in <module>
    import dvc.api
ModuleNotFoundError: No module named 'dvc'
[2024-11-26T18:09:08.005+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:09:08.021+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.038 seconds
[2024-11-26T18:09:34.993+0000] {processor.py:186} INFO - Started process (PID=506) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:09:34.994+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:09:34.995+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:09:34.995+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:09:35.016+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:09:35.013+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Airflow-DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Airflow-DAG.py", line 5, in <module>
    from sklearn.linear_model import LinearRegression
ModuleNotFoundError: No module named 'sklearn'
[2024-11-26T18:09:35.017+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:09:35.031+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.041 seconds
[2024-11-26T18:11:04.972+0000] {processor.py:186} INFO - Started process (PID=696) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:11:04.973+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:11:04.974+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:11:04.973+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:11:04.993+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:11:04.990+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Airflow-DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Airflow-DAG.py", line 5, in <module>
    from sklearn.linear_model import LinearRegression
ModuleNotFoundError: No module named 'sklearn'
[2024-11-26T18:11:04.994+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:11:05.008+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.039 seconds
[2024-11-26T18:11:35.775+0000] {processor.py:186} INFO - Started process (PID=766) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:11:35.776+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:11:35.777+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:11:35.776+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:11:35.790+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:11:35.787+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Airflow-DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Airflow-DAG.py", line 5, in <module>
    from sklearn.linear_model import LinearRegression
ModuleNotFoundError: No module named 'sklearn'
[2024-11-26T18:11:35.791+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:11:35.805+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.033 seconds
[2024-11-26T18:12:29.625+0000] {processor.py:186} INFO - Started process (PID=51) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:12:29.626+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:12:29.628+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:12:29.628+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:12:29.646+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:12:29.642+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Airflow-DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Airflow-DAG.py", line 5, in <module>
    from sklearn.linear_model import LinearRegression
ModuleNotFoundError: No module named 'sklearn'
[2024-11-26T18:12:29.648+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:12:29.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.046 seconds
[2024-11-26T18:13:00.400+0000] {processor.py:186} INFO - Started process (PID=115) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:13:00.401+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:13:00.403+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:13:00.402+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:13:00.417+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:13:00.413+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Airflow-DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Airflow-DAG.py", line 5, in <module>
    from sklearn.linear_model import LinearRegression
ModuleNotFoundError: No module named 'sklearn'
[2024-11-26T18:13:00.419+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:13:00.436+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.040 seconds
[2024-11-26T18:13:31.093+0000] {processor.py:186} INFO - Started process (PID=179) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:13:31.094+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:13:31.095+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:13:31.095+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:13:31.108+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:13:31.106+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Airflow-DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Airflow-DAG.py", line 5, in <module>
    from sklearn.linear_model import LinearRegression
ModuleNotFoundError: No module named 'sklearn'
[2024-11-26T18:13:31.110+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:13:31.126+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.037 seconds
[2024-11-26T18:14:01.242+0000] {processor.py:186} INFO - Started process (PID=243) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:14:01.243+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:14:01.245+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:14:01.245+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:14:01.262+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:14:01.259+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Airflow-DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Airflow-DAG.py", line 5, in <module>
    from sklearn.linear_model import LinearRegression
ModuleNotFoundError: No module named 'sklearn'
[2024-11-26T18:14:01.263+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:14:01.279+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.041 seconds
[2024-11-26T18:14:31.392+0000] {processor.py:186} INFO - Started process (PID=307) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:14:31.392+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:14:31.394+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:14:31.394+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:14:31.407+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:14:31.404+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Airflow-DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Airflow-DAG.py", line 5, in <module>
    from sklearn.linear_model import LinearRegression
ModuleNotFoundError: No module named 'sklearn'
[2024-11-26T18:14:31.408+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:14:31.422+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.034 seconds
[2024-11-26T18:15:02.249+0000] {processor.py:186} INFO - Started process (PID=371) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:15:02.250+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:15:02.251+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:15:02.251+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:15:02.267+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:15:02.262+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Airflow-DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Airflow-DAG.py", line 5, in <module>
    from sklearn.linear_model import LinearRegression
ModuleNotFoundError: No module named 'sklearn'
[2024-11-26T18:15:02.269+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:15:02.285+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.040 seconds
[2024-11-26T18:15:33.007+0000] {processor.py:186} INFO - Started process (PID=441) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:15:33.008+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:15:33.010+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:15:33.010+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:15:33.025+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:15:33.021+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Airflow-DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Airflow-DAG.py", line 5, in <module>
    from sklearn.linear_model import LinearRegression
ModuleNotFoundError: No module named 'sklearn'
[2024-11-26T18:15:33.026+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:15:33.042+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.039 seconds
[2024-11-26T18:16:03.894+0000] {processor.py:186} INFO - Started process (PID=505) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:16:03.895+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:16:03.897+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:16:03.897+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:16:03.912+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:16:03.909+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Airflow-DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Airflow-DAG.py", line 5, in <module>
    from sklearn.linear_model import LinearRegression
ModuleNotFoundError: No module named 'sklearn'
[2024-11-26T18:16:03.913+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:16:03.927+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.038 seconds
[2024-11-26T18:16:34.492+0000] {processor.py:186} INFO - Started process (PID=569) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:16:34.493+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:16:34.495+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:16:34.494+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:16:34.508+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:16:34.505+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Airflow-DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Airflow-DAG.py", line 5, in <module>
    from sklearn.linear_model import LinearRegression
ModuleNotFoundError: No module named 'sklearn'
[2024-11-26T18:16:34.509+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:16:34.523+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.034 seconds
[2024-11-26T18:17:05.259+0000] {processor.py:186} INFO - Started process (PID=633) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:17:05.260+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:17:05.263+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:17:05.262+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:17:05.284+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:17:05.280+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Airflow-DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Airflow-DAG.py", line 5, in <module>
    from sklearn.linear_model import LinearRegression
ModuleNotFoundError: No module named 'sklearn'
[2024-11-26T18:17:05.286+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:17:05.304+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.052 seconds
[2024-11-26T18:17:36.031+0000] {processor.py:186} INFO - Started process (PID=697) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:17:36.032+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:17:36.034+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:17:36.034+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:17:36.047+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:17:36.044+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Airflow-DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Airflow-DAG.py", line 5, in <module>
    from sklearn.linear_model import LinearRegression
ModuleNotFoundError: No module named 'sklearn'
[2024-11-26T18:17:36.048+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:17:36.062+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.034 seconds
[2024-11-26T18:18:07.000+0000] {processor.py:186} INFO - Started process (PID=761) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:18:07.001+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:18:07.003+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:18:07.003+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:18:07.016+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:18:07.013+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Airflow-DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Airflow-DAG.py", line 5, in <module>
    from sklearn.linear_model import LinearRegression
ModuleNotFoundError: No module named 'sklearn'
[2024-11-26T18:18:07.017+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:18:07.032+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.037 seconds
[2024-11-26T18:44:08.283+0000] {processor.py:186} INFO - Started process (PID=57) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:44:08.284+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:44:08.287+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:44:08.287+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:44:08.823+0000] {processor.py:925} INFO - DAG(s) 'weather_data_pipeline' retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:44:09.273+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:44:09.272+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:weather_data_pipeline
[2024-11-26T18:44:09.284+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:44:09.284+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:weather_data_pipeline
[2024-11-26T18:44:09.292+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:44:09.291+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:weather_data_pipeline
[2024-11-26T18:44:09.300+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:44:09.300+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:weather_data_pipeline
[2024-11-26T18:44:09.307+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:44:09.306+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:weather_data_pipeline
[2024-11-26T18:44:09.317+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:44:09.317+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:weather_data_pipeline
[2024-11-26T18:44:09.324+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:44:09.324+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:weather_data_pipeline
[2024-11-26T18:44:09.325+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:44:09.325+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T18:44:09.335+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:44:09.334+0000] {dag.py:3262} INFO - Creating ORM DAG for weather_data_pipeline
[2024-11-26T18:44:09.344+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:44:09.344+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_data_pipeline to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T18:44:09.361+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 1.088 seconds
[2024-11-26T18:44:39.757+0000] {processor.py:186} INFO - Started process (PID=134) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:44:39.757+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:44:39.759+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:44:39.758+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:44:40.218+0000] {processor.py:925} INFO - DAG(s) 'weather_data_pipeline' retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:44:40.237+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:44:40.237+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T18:44:40.417+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:44:40.417+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_data_pipeline to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T18:44:40.431+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.678 seconds
[2024-11-26T18:45:11.189+0000] {processor.py:186} INFO - Started process (PID=218) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:45:11.189+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:45:11.191+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:45:11.191+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:45:11.669+0000] {processor.py:925} INFO - DAG(s) 'weather_data_pipeline' retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:45:11.684+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:45:11.684+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T18:45:11.703+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:45:11.703+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_data_pipeline to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T18:45:11.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.695 seconds
[2024-11-26T18:45:42.750+0000] {processor.py:186} INFO - Started process (PID=293) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:45:42.751+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:45:42.752+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:45:42.752+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:45:43.513+0000] {processor.py:925} INFO - DAG(s) 'weather_data_pipeline' retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:45:43.536+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:45:43.535+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T18:45:43.558+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:45:43.558+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_data_pipeline to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T18:45:43.579+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.834 seconds
[2024-11-26T18:46:14.210+0000] {processor.py:186} INFO - Started process (PID=369) to work on /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:46:14.211+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Airflow-DAG.py for tasks to queue
[2024-11-26T18:46:14.213+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:46:14.212+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:46:14.816+0000] {processor.py:925} INFO - DAG(s) 'weather_data_pipeline' retrieved from /opt/airflow/dags/Airflow-DAG.py
[2024-11-26T18:46:14.830+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:46:14.829+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T18:46:14.846+0000] {logging_mixin.py:190} INFO - [2024-11-26T18:46:14.846+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_data_pipeline to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T18:46:14.862+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Airflow-DAG.py took 0.656 seconds
